package no.ntnu.iir.idata2304.iot.apps.ingest.model;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MappedSuperclass;

import org.hibernate.annotations.CreationTimestamp;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a super class for measurement entities.
 * Any entities that are meant to be persisted, can extend this class.
 * This is not a direct entity, it's sole purpose is to provide a common 
 * structure different types of measurements.
 */
@Getter
@Setter
@MappedSuperclass
@NoArgsConstructor
public class Measurement {

  public static final String PRIMARY_KEY = "measurement_id";

  @Id
  @Setter(AccessLevel.NONE) // generated by the database, should not be overridden
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = Measurement.PRIMARY_KEY)
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "fk_sensor_id", referencedColumnName = "sensor_id")
  @JoinColumn(name = "fk_sensor_place", referencedColumnName = "place")
  @JoinColumn(name = "fk_sensor_room", referencedColumnName = "room")
  private Sensor sensor;

  @CreationTimestamp
  @Column(name = "measured_at", nullable = false)
  private Date measuredAt;

}
